import Head from 'next/head'
import DeskNavbar from '../components/navigation/DeskNavbar'
import NotificationToasts from '../components/navigation/NotificationToasts'
import SubscribeModal from '../components/modal/SubscribeModal'
import Banner from '../components/banner/Banner'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overlay"></div>
      <SubscribeModal />
      <NotificationToasts />
      <DeskNavbar />
      <Banner />
    </div>
  )
}
